# Generated by Django 5.0.2 on 2024-02-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('details', models.CharField(max_length=300, null=True)),
                ('price_group_id', models.PositiveSmallIntegerField()),
                ('pmaterial_type_id', models.PositiveSmallIntegerField()),
                ('ptype_id', models.PositiveSmallIntegerField()),
                ('pstate_id', models.PositiveSmallIntegerField()),
                ('gender_id', models.PositiveSmallIntegerField()),
                ('brand_id', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
