# Generated by Django 5.0.2 on 2024-02-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_alter_product_brand_id_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('special_status', 'Can see all products')]},
        ),
    ]
